apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentName }}
    build_number: {{ .Values.buildNumber }} # jenkins build number
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
      - name: {{ .Values.deploymentName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }} # the tag is passed from cli in jenkins
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        env:
          - name: LISTENING_PORT
            value: "{{ .Values.ports.listeningPort }}"
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}