apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
spec:
  selector:
    app: {{ .Values.deploymentName }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.containerPort }}
      protocol: TCP
      name: http