kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.deploymentName }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.deploymentName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}