apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      serviceAccount: {{ .Values.deploymentName }}
      serviceAccountName: {{ .Values.deploymentName }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{ .Values.deploymentName }}
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "{{ .Values.daemonSet.env.elasticsearchHost }}"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "{{ .Values.daemonSet.env.elasticsearchPort }}"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "{{ .Values.daemonSet.env.elasticsearchScheme }}"
          - name: FLUENTD_SYSTEMD_CONF
            value: "{{ .Values.daemonSet.env.fluentdSystemdConf }}"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers