deploymentName: "http-service"

replicaCount: 1

image:
  repository: erizzardi/http-service
  pullPolicy: IfNotPresent
  tag: latest

ports:
  containerPort: 8081
  listeningPort: 8081

ingress:
  name: nginx-ingress
  hostName: http-service.int

terminationGracePeriodSeconds: 30


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi