deploymentName: "http-service"

replicaCount: 1

image:
  repository: erizzardi/http-service
  pullPolicy: IfNotPresent
  tag: latest

ports:
  containerPort: 8080
  listeningPort: 8080

ingress:
  name: nginx-ingress
  hostName: http-service.int

terminationGracePeriodSeconds: 30


resources:
  limits:
    cpu: 100m
    memory: 128Mi