deploymentName: fluentd
namespace: logging

daemonSet:
  env:
    elasticsearchHost: "elasticsearch-master.{{ .Values.namespace }}.svc.cluster.local"
    elasticsearchPort: "9200"
    elasticsearchScheme: "http"
    fluentdSystemdConf: disable

