deploymentName: fluentd
namespace: monitoring

terminationGracePeriodSeconds: 30

daemonSet:
  env:
    elasticsearchHost: elasticsearch-master.monitoring.svc.cluster.local
    elasticsearchPort: 9200
    elasticsearchScheme: http

